$(document).ready(function(){
$('.gallery').click(function(){
    $('#gallery').show();
    $("#aboutUs").hide();
});
$('.aboutUs').click(function(){
    $('#aboutUs').show();
    $("#gallery").hide();
});
});